myapp/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    # admin and basic urls
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('FAQ/', views.FAQ, name='FAQ'),

    # user acc urls
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('logout/', views.logout, name='logout'),

    # product urls
    path('products/', views.products, name='products'),
    path('product_search/', views.product_search, name='product_search'),
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:product_id>/', views.update_cart, name='update_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),

    # Equipments
    path('equipments/', views.equipments, name='equipments'),
    path('equipment_search/', views.equipment_search, name='equipment_search'),
    path('cart1/', views.cart1, name='cart1'),
    path('add_to_cart1/<int:equipment_id>/', views.add_to_cart1, name='add_to_cart1'),
    path('update_cart1/<int:equipment_id>/', views.update_cart1, name='update_cart1'),
    path('remove_from_cart1/<int:equipment_id>/', views.remove_from_cart1, name='remove_from_cart1'),
    path('checkout1/', views.checkout1, name='checkout1'),

    # doctor appointment urls
    path('doctors/', views.doctors, name='doctors'),
    path('doctor_search/', views.doctor_search, name='doctor_search'),
    path('create_appointment/<int:doctor_id>/', views.create_appointment, name='create_appointment'),
    path('cancel_appointment/<int:appointment_id>/<int:doctor_id>/', views.cancel_appointment,
         name='cancel_appointment'),

    # emergency urls not done
    # path('emergency/', views.emergency, name='emergency'),
    path('donors/', views.donors, name='donors'),
    path('blood_search/', views.blood_search, name='blood_search'),

    # error handaling urls
    path('custom_error/', views.custom_error, name='custom_error'),
    path('<path:undefined_path>/', RedirectView.as_view(url='/custom_error/')),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('myapp.urls')),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import pre_delete
from django.utils import timezone

# userprofile start
class UserProfile(models.Model):
    def __str__(self):
        return self.fullname()

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def fullname(self):
        return f"{self.user.first_name} {self.user.last_name}"

    age = models.IntegerField()
    address = models.CharField(max_length=255)
    mobile = models.CharField(max_length=15)
    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    gender = models.CharField(max_length=10, choices=GENDER)


@receiver(pre_delete, sender=User)
def delete_user_profile(sender, instance, **kwargs):
    try:
        profile = UserProfile.objects.get(user=instance)
        profile.delete()
    except UserProfile.DoesNotExist:
        pass


# Medicine part start
class Medicines(models.Model):
    def __str__(self):
        return self.p_name

    p_image = models.ImageField()
    p_name = models.CharField(max_length=100)
    p_description = models.CharField(max_length=1000)
    p_cost = models.IntegerField()
    p_count = models.IntegerField()
    v_name = models.CharField(max_length=100)
    v_description = models.CharField(max_length=100)


class CartItem(models.Model):
    def __str__(self):
        return self.user.username

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    accessory = models.ForeignKey(Medicines, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    total_cost = models.IntegerField(null=True)


class Bill(models.Model):
    def __str__(self):
        return f"{self.customer.username} - {self.created_at}"

    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(default=timezone.now)
    accessories = models.ManyToManyField(Medicines, through='BillItem')


class BillItem(models.Model):
    bill = models.ForeignKey(Bill, on_delete=models.CASCADE)
    accessory = models.ForeignKey(Medicines, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)


# doctor modal started
class Doctor(models.Model):
    def __str__(self):
        return self.name

    image = models.ImageField()
    name = models.CharField(max_length=255)
    specialty = models.CharField(max_length=255)
    status = models.BooleanField(default=True)
    cost = models.IntegerField()
    available_spots = models.PositiveIntegerField()
    next_available_appointment_date = models.DateField(null=True, blank=True)


class DoctorTimeSlot(models.Model):
    def __str__(self):
        return f"{self.doctor.name} ({self.start_time} - {self.end_time})"

    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    start_time = models.TimeField()
    end_time = models.TimeField()


class Appointment(models.Model):
    def __str__(self):
        return self.user.username

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    doctor_time_slot = models.ForeignKey(DoctorTimeSlot, on_delete=models.CASCADE)
    description = models.CharField(max_length=1000)
    appointment_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    serial_number = models.PositiveIntegerField(default=0)


# Donor Start Here

class Donor(models.Model):
    BLOOD_GROUP_CHOICES = (
        ('A+', 'A+'),
        ('B+', 'B+'),
        ('AB+', 'AB+'),
        ('O+', 'O+'),
        ('A-', 'A-'),
        ('B-', 'B-'),
        ('AB-', 'AB-'),
        ('O-', 'O-'),
    )

    name = models.CharField(max_length=100)
    age = models.PositiveIntegerField()
    bloodgroup = models.CharField(max_length=20, choices=BLOOD_GROUP_CHOICES)
    email = models.EmailField()
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=100)
    weight = models.PositiveIntegerField()
    previous_donation_date = models.DateField()

    def __str__(self):
        return self.name


# Equipment start

class Equipments(models.Model):
    def __str__(self):
        return self.e_name

    e_image = models.ImageField()
    e_name = models.CharField(max_length=100)
    e_description = models.CharField(max_length=1000)
    e_cost = models.IntegerField()
    e_count = models.IntegerField()
    vendor_name = models.CharField(max_length=100)
    vendor_description = models.CharField(max_length=100)


class CartItem1(models.Model):
    def __str__(self):
        return self.user.username

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    accessory1 = models.ForeignKey(Equipments, on_delete=models.CASCADE)
    quantity1 = models.IntegerField(default=1)
    total_cost1 = models.IntegerField(null=True)


class Bill1(models.Model):
    def __str__(self):
        return f"{self.customer.username} - {self.created_at}"

    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    total_cost1 = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(default=timezone.now)
    accessories1 = models.ManyToManyField(Equipments, through='BillItem1')


class BillItem1(models.Model):
    bill1 = models.ForeignKey(Bill1, on_delete=models.CASCADE)
    accessory1 = models.ForeignKey(Equipments, on_delete=models.CASCADE)
    quantity1 = models.IntegerField()
    total_cost1 = models.DecimalField(max_digits=10, decimal_places=2)

# Equipments end




myapp/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User
from django_recaptcha.fields import ReCaptchaField


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['age', 'address', 'mobile', 'gender']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class Captcha(forms.Form):
    captcha = ReCaptchaField()

myapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<!-- Title -->
	  <link rel="icon" href="{% static 'img/favicon.png' %}">
      <title>Digital HealthCare</title>

	  <link rel="stylesheet" href="{% static 'css/style.css'%}">
      <link rel="stylesheet" href="{% static 'css/all.min.css'%}">
	   {% block extra-styles %}  {% endblock %}
  </head>

    <body>

	<!-- Nav Bar Start-->
    <nav>
      <div class="nav__header">
        <div class="nav__logo">
			<a href="#">Digital<span>HealthCare</span></a>
        </div>
        <div class="nav__menu__btn" id="menu-btn">
          <span><i class="ri-menu-line"></i></span>
        </div>
      </div>
      <ul class="nav__links" id="nav-links">
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Reviews</a></li>
        <li><a href="#">Contacts</a></li>
      </ul>
		<div  class="nav__btns">
			{% if user.is_authenticated %}
			      {% if user.is_superuser %}
			          <button class="btn sign__up"><a href="{% url 'admin:index' %}" >Admin Panel</a></button>
                  {% else %}
			<button class="btn sign__up"><a href="{% url 'user_profile' %}" >{{ user.username }}</a></button>
			 	  {% endif %}
			{% else %}
				<button class="btn sign__up">  <a href="{% url 'login' %}">Login</a></button>
			{% endif %}
<!--        <button class="btn sign__up">Sign Up</button>-->
<!--        <button class="btn sign__in">Sign In</button>-->
			{% if user.is_authenticated %}
			      {% if user.is_superuser %}
			          <button class="btn sign__in"><a href="{% url 'logout' %}" >Sign out</a></button>
                  {% else %}
			<button class="btn sign__in"><a href="{% url 'logout' %}" >Sign out</a></button>
			 	  {% endif %}
			{% else %}
				<button class="btn sign__in">  <a href="{% url 'register' %}">Sign-up</a></button>
			{% endif %}
		</div>
	</nav>

<!-- Nav Bar end-->




{% block content %}




{% endblock %}





<!--Footer Start-->
	<section class="footer">
		<div class="box-container">
			<div class="box">
				<h3>quick links</h3>
				<a href="#">home</a>
				<a href="#">about</a>
				<a href="#">services</a>
				<a href="#">reviews</a>
				<a href="#">blogs</a>
				<a href="#">contact</a>
			</div>

			<div class="box">
				<h3>services offered</h3>
				<a href="#">CT scan</a>
				<a href="#">diagnosis</a>
				<a href="#">ambulance services</a>
				<a href="#">children's clinic</a>
				<a href="#">pharmacy</a>
				<a href="#">dental care</a>
			</div>

			<div class="box">
				<h3>our socials</h3>
				<a href="#"><i class="fab fa-facebook"></i> facebook</a>
				<a href="#"><i class="fab fa-twitter"></i> twitter</a>
				<a href="#"><i class="fab fa-instagram"></i> instagram</a>
				<a href="#"><i class="fab fa-linkedin"></i> linkedin</a>
			</div>
		</div>

		<div class="bottom">&copy; 2024 all rights reserved | <span> Error404 </span></div>
	</section>
  <!--Footer Start-->

     </body>
</html>

myapp/templates/blood_donors.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css '%}">

	  <link rel="icon" href="{% static 'img/favicon.png' %}">
    <title>Digital HealthCare</title>

      <link rel="stylesheet" href="{% static 'css/style.css'%}">
      <link rel="stylesheet" href="{% static 'css/all.min.css'%}">

  </head>
  <body>




<!-- Nav Bar Start-->
    <nav>
      <div class="nav__header">
        <div class="nav__logo">
			<a href="#">Digital<span>HealthCare</span></a>
        </div>
        <div class="nav__menu__btn" id="menu-btn">
          <span><i class="ri-menu-line"></i></span>
        </div>
      </div>
      <ul class="nav__links" id="nav-links">
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Reviews</a></li>
        <li><a href="#">Contacts</a></li>
      </ul>
		<div  class="nav__btns">
			{% if user.is_authenticated %}
			      {% if user.is_superuser %}
			          <button class="btn sign__up"><a href="{% url 'admin:index' %}" >Admin Panel</a></button>
                  {% else %}
			<button class="btn sign__up"><a href="{% url 'user_profile' %}" >{{ user.username }}</a></button>
			 	  {% endif %}
			{% else %}
				<button class="btn sign__up">  <a href="{% url 'login' %}">Login</a></button>
			{% endif %}
			{% if user.is_authenticated %}
			      {% if user.is_superuser %}
			          <button class="btn sign__in"><a href="{% url 'logout' %}" >Sign out</a></button>
                  {% else %}
			<button class="btn sign__in"><a href="{% url 'logout' %}" >Sign out</a></button>
			 	  {% endif %}
			{% else %}
				<button class="btn sign__in">  <a href="{% url 'register' %}">Sign-up</a></button>
			{% endif %}
		</div>
	</nav>

<!--Navbar end-->









  <!--Footer Start-->
	<section class="footer">
		<div class="box-container">
			<div class="box">
				<h3>quick links</h3>
				<a href="#">home</a>
				<a href="#">about</a>
				<a href="#">services</a>
				<a href="#">reviews</a>
				<a href="#">blogs</a>
				<a href="#">contact</a>
			</div>

			<div class="box">
				<h3>services offered</h3>
				<a href="#">CT scan</a>
				<a href="#">diagnosis</a>
				<a href="#">ambulance services</a>
				<a href="#">children's clinic</a>
				<a href="#">pharmacy</a>
				<a href="#">dental care</a>
			</div>

			<div class="box">
				<h3>our socials</h3>
				<a href="#"><i class="fab fa-facebook"></i> facebook</a>
				<a href="#"><i class="fab fa-twitter"></i> twitter</a>
				<a href="#"><i class="fab fa-instagram"></i> instagram</a>
				<a href="#"><i class="fab fa-linkedin"></i> linkedin</a>
			</div>
		</div>

		<div class="bottom">&copy; 2024 all rights reserved | <span> Error404 </span></div>
	</section>
  <!--Footer Start-->
  </body>
</html>


myapp/templates/cart.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css '%}">

	  <link rel="icon" href="{% static 'img/favicon.png' %}">
    <title>Digital HealthCare</title>

      <link rel="stylesheet" href="{% static 'css/style.css'%}">
      <link rel="stylesheet" href="{% static 'css/all.min.css'%}">

  </head>
  <body>




<!-- Nav Bar Start-->
    <nav>
      <div class="nav__header">
        <div class="nav__logo">
			<a href="#">Digital<span>HealthCare</span></a>
        </div>
        <div class="nav__menu__btn" id="menu-btn">
          <span><i class="ri-menu-line"></i></span>
        </div>
      </div>
      <ul class="nav__links" id="nav-links">
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Reviews</a></li>
        <li><a href="#">Contacts</a></li>
      </ul>
		<div  class="nav__btns">
			{% if user.is_authenticated %}
			      {% if user.is_superuser %}
			          <button class="btn sign__up"><a href="{% url 'admin:index' %}" >Admin Panel</a></button>
                  {% else %}
			<button class="btn sign__up"><a href="{% url 'user_profile' %}" >{{ user.username }}</a></button>
			 	  {% endif %}
			{% else %}
				<button class="btn sign__up">  <a href="{% url 'login' %}">Login</a></button>
			{% endif %}
			{% if user.is_authenticated %}
			      {% if user.is_superuser %}
			          <button class="btn sign__in"><a href="{% url 'logout' %}" >Sign out</a></button>
                  {% else %}
			<button class="btn sign__in"><a href="{% url 'logout' %}" >Sign out</a></button>
			 	  {% endif %}
			{% else %}
				<button class="btn sign__in">  <a href="{% url 'register' %}">Sign-up</a></button>
			{% endif %}
		</div>
	</nav>

<!--Navbar end-->






  <!--Footer Start-->
	<section class="footer">
		<div class="box-container">
			<div class="box">
				<h3>quick links</h3>
				<a href="#">home</a>
				<a href="#">about</a>
				<a href="#">services</a>
				<a href="#">reviews</a>
				<a href="#">blogs</a>
				<a href="#">contact</a>
			</div>

			<div class="box">
				<h3>services offered</h3>
				<a href="#">CT scan</a>
				<a href="#">diagnosis</a>
				<a href="#">ambulance services</a>
				<a href="#">children's clinic</a>
				<a href="#">pharmacy</a>
				<a href="#">dental care</a>
			</div>

			<div class="box">
				<h3>our socials</h3>
				<a href="#"><i class="fab fa-facebook"></i> facebook</a>
				<a href="#"><i class="fab fa-twitter"></i> twitter</a>
				<a href="#"><i class="fab fa-instagram"></i> instagram</a>
				<a href="#"><i class="fab fa-linkedin"></i> linkedin</a>
			</div>
		</div>

		<div class="bottom">&copy; 2024 all rights reserved | <span> Error404 </span></div>
	</section>
  <!--Footer Start-->
  </body>
</html>


myapp/templates/cart1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css '%}">

	  <link rel="icon" href="{% static 'img/favicon.png' %}">
    <title>Digital HealthCare</title>

      <link rel="stylesheet" href="{% static 'css/style.css'%}">
      <link rel="stylesheet" href="{% static 'css/all.min.css'%}">

  </head>
  <body>




<!-- Nav Bar Start-->
    <nav>
      <div class="nav__header">
        <div class="nav__logo">
			<a href="#">Digital<span>HealthCare</span></a>
        </div>
        <div class="nav__menu__btn" id="menu-btn">
          <span><i class="ri-menu-line"></i></span>
        </div>
      </div>
      <ul class="nav__links" id="nav-links">
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Reviews</a></li>
        <li><a href="#">Contacts</a></li>
      </ul>
		<div  class="nav__btns">
			{% if user.is_authenticated %}
			      {% if user.is_superuser %}
			          <button class="btn sign__up"><a href="{% url 'admin:index' %}" >Admin Panel</a></button>
                  {% else %}
			<button class="btn sign__up"><a href="{% url 'user_profile' %}" >{{ user.username }}</a></button>
			 	  {% endif %}
			{% else %}
				<button class="btn sign__up">  <a href="{% url 'login' %}">Login</a></button>
			{% endif %}
			{% if user.is_authenticated %}
			      {% if user.is_superuser %}
			          <button class="btn sign__in"><a href="{% url 'logout' %}" >Sign out</a></button>
                  {% else %}
			<button class="btn sign__in"><a href="{% url 'logout' %}" >Sign out</a></button>
			 	  {% endif %}
			{% else %}
				<button class="btn sign__in">  <a href="{% url 'register' %}">Sign-up</a></button>
			{% endif %}
		</div>
	</nav>

<!--Navbar end-->





  <!--Footer Start-->
	<section class="footer">
		<div class="box-container">
			<div class="box">
				<h3>quick links</h3>
				<a href="#">home</a>
				<a href="#">about</a>
				<a href="#">services</a>
				<a href="#">reviews</a>
				<a href="#">blogs</a>
				<a href="#">contact</a>
			</div>

			<div class="box">
				<h3>services offered</h3>
				<a href="#">CT scan</a>
				<a href="#">diagnosis</a>
				<a href="#">ambulance services</a>
				<a href="#">children's clinic</a>
				<a href="#">pharmacy</a>
				<a href="#">dental care</a>
			</div>

			<div class="box">
				<h3>our socials</h3>
				<a href="#"><i class="fab fa-facebook"></i> facebook</a>
				<a href="#"><i class="fab fa-twitter"></i> twitter</a>
				<a href="#"><i class="fab fa-instagram"></i> instagram</a>
				<a href="#"><i class="fab fa-linkedin"></i> linkedin</a>
			</div>
		</div>

		<div class="bottom">&copy; 2024 all rights reserved | <span> Error404 </span></div>
	</section>
  <!--Footer Start-->
  </body>
</html>


myapp/templates/doctors.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css '%}">

	  <link rel="icon" href="{% static 'img/favicon.png' %}">
    <title>Digital HealthCare</title>

      <link rel="stylesheet" href="{% static 'css/style.css'%}">
      <link rel="stylesheet" href="{% static 'css/all.min.css'%}">

  </head>
  <body>




<!-- Nav Bar Start-->
    <nav>
      <div class="nav__header">
        <div class="nav__logo">
			<a href="#">Digital<span>HealthCare</span></a>
        </div>
        <div class="nav__menu__btn" id="menu-btn">
          <span><i class="ri-menu-line"></i></span>
        </div>
      </div>
      <ul class="nav__links" id="nav-links">
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Reviews</a></li>
        <li><a href="#">Contacts</a></li>
      </ul>
		<div  class="nav__btns">
			{% if user.is_authenticated %}
			      {% if user.is_superuser %}
			          <button class="btn sign__up"><a href="{% url 'admin:index' %}" >Admin Panel</a></button>
                  {% else %}
			<button class="btn sign__up"><a href="{% url 'user_profile' %}" >{{ user.username }}</a></button>
			 	  {% endif %}
			{% else %}
				<button class="btn sign__up">  <a href="{% url 'login' %}">Login</a></button>
			{% endif %}
			{% if user.is_authenticated %}
			      {% if user.is_superuser %}
			          <button class="btn sign__in"><a href="{% url 'logout' %}" >Sign out</a></button>
                  {% else %}
			<button class="btn sign__in"><a href="{% url 'logout' %}" >Sign out</a></button>
			 	  {% endif %}
			{% else %}
				<button class="btn sign__in">  <a href="{% url 'register' %}">Sign-up</a></button>
			{% endif %}
		</div>
	</nav>



<!--Content PART start-->


<!--    search  features start -->

        <form id="search-form" action="{% url 'doctor_search' %}" method="get">
            <input type="text" id="search-input" name="q" placeholder="Search doctors...">
            <button type="submit" id="search-button">Search</button>
        </form>

<!--search end-->

        {% if doctors %}
            {% for doctor in doctors %}

                        <img src="{% static 'img/'|add:doctor.image.url %}" alt="Doctor Image">


                        <h1 >{{ doctor.name }}</h1>
                        <p  >{{ doctor.specialty }}</p>
                        <p >Payment: {{ doctor.cost }}</p>


                        <
                            <strong>Patient bookings left: {{doctor.available_spots}}</strong>

                        <h2>Appointment Slots</h2>
                        <ul>
                            {% for slot in doctor.doctortimeslot_set.all %}
                                <li>
                                    <strong>Time:</strong> {{ slot.start_time }} - {{ slot.end_time }}
                                </li>
                            {% endfor %}
                        </ul>

                        {% if not doctor.status %}
                            {% if next_available_slot %}

                                    <p><strong>Next Available Slot:</strong> {{ next_available_slot.start_time }} - {{ next_available_slot.end_time }}</p>
                                    <a  href="{% url 'create_appointment' doctor.id %}" >Create Appointment</a>

                            {% endif %}
                        {% endif %}


                        {% if doctor.available_spots > 0 and doctor.status %}
                            <a  href="{% url 'create_appointment' doctor.id %}">Create Appointment</a>
                        {% else %}
                            <span >Unavailable</span>
                            {% if not doctor.status %}
                                <a href="{% url 'create_appointment' doctor.id %}" >Additional Information</a>
                            {% endif %}
                        {% endif %}


            {% endfor %}
        {% endif %}



<!--Contet PART END-->
<!--Footer Start-->
	<section class="footer">
		<div class="box-container">
			<div class="box">
				<h3>quick links</h3>
				<a href="#">home</a>
				<a href="#">about</a>
				<a href="#">services</a>
				<a href="#">reviews</a>
				<a href="#">blogs</a>
				<a href="#">contact</a>
			</div>

			<div class="box">
				<h3>services offered</h3>
				<a href="#">CT scan</a>
				<a href="#">diagnosis</a>
				<a href="#">ambulance services</a>
				<a href="#">children's clinic</a>
				<a href="#">pharmacy</a>
				<a href="#">dental care</a>
			</div>

			<div class="box">
				<h3>our socials</h3>
				<a href="#"><i class="fab fa-facebook"></i> facebook</a>
				<a href="#"><i class="fab fa-twitter"></i> twitter</a>
				<a href="#"><i class="fab fa-instagram"></i> instagram</a>
				<a href="#"><i class="fab fa-linkedin"></i> linkedin</a>
			</div>
		</div>

		<div class="bottom">&copy; 2024 all rights reserved | <span> Error404 </span></div>
	</section>
  <!--Footer Start-->
  </body>
</html>